"""document items and project_brief type

Revision ID: bff93959505e
Revises: bb2ab5bdb07d
Create Date: 2026-05-27 12:04:50.912417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bff93959505e'
down_revision: Union[str, Sequence[str], None] = 'bb2ab5bdb07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # New artifact type for the project-brief root document (native enum value).
    op.execute("ALTER TYPE artifact_type ADD VALUE IF NOT EXISTS 'project_brief'")
    # Structured items on documents and their version snapshots.
    op.add_column('artifact_versions', sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('artifacts', sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'items')
    op.drop_column('artifact_versions', 'items')
    # ### end Alembic commands ###
